// GET /wanted — the public board: solicitations whose want was marked public, nothing else. Private
// wants never appear here. A provider answers with OFFER_NEW.
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export async function onRequestGet({ request, env }) {
  const origin = new URL(request.url).origin;
  let rows = [], failed = null;
  try { rows = (await env.DB.prepare("SELECT s.id, s.scope, s.budget_class, s.evidence_required, s.deadline, s.created_at, (SELECT COUNT(*) FROM market_offers o WHERE o.solicitation_id = s.id AND o.state = 'open') AS offers FROM market_solicitations s JOIN market_wants w ON w.id = s.want_id WHERE s.mode = 'public' AND w.public = 1 AND s.state = 'open' ORDER BY s.created_at DESC LIMIT 100").all()).results || []; } catch (e) { failed = String(e?.message || e); }
  const body = failed ? `<tr><td colspan="6">LEDGER_LOOKUP_FAILED: the store did not answer; the board may not be empty.</td></tr>` : rows.map((r) => `<tr><td>${esc(r.created_at).slice(0, 10)}</td><td>${esc(r.scope)}</td><td>${esc(r.budget_class)}</td><td>${esc(r.evidence_required)}</td><td>${esc(r.deadline || '')}</td><td>${r.offers} · <code>OFFER_NEW ${esc(r.id)}|…</code></td></tr>`).join('') || '<tr><td colspan="6">Nothing is posted publicly. Wants are private unless their owner marks them public.</td></tr>';
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wanted</title><style>body{font:16px/1.55 -apple-system,system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1a1a1a;background:#fbfaf7}table{width:100%;border-collapse:collapse;font-size:.92em}td,th{border-bottom:1px solid #ddd;padding:.45rem;text-align:left;vertical-align:top}code{background:#f0ede6;border-radius:6px;padding:.1rem .3rem}.muted{color:#555}</style></head><body><p class="muted">miscsubjects · wanted</p><h1>Wanted</h1><p>Outcomes people have asked for and chosen to post. A provider answers with an offer that names its scope, method, price, timing, evidence and whether the work is human, AI or hybrid: <code>POST ${origin}/api/dispatch {"key":"OFFER_NEW","body":"&lt;solicitation_id&gt;|&lt;your profile&gt;|&lt;scope&gt;|&lt;method&gt;|&lt;price_usd&gt;|&lt;timing&gt;|&lt;evidence&gt;|human|ai|hybrid|&lt;authority_grade&gt;"}</code>. The buyer's AI ranks offers into a set under the buyer's trust policy; payment never buys trust.</p><table><thead><tr><th>posted</th><th>scope</th><th>budget class</th><th>evidence required</th><th>deadline</th><th>open offers</th></tr></thead><tbody>${body}</tbody></table><p class="muted"><a href="${origin}/a/capability-network-charter">The Capability Network Charter</a> · <a href="${origin}/challenge">The Challenge</a></p></body></html>`;
  return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } });
}
