function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
function links(values) {
  return (values || []).map(url => `<a href="${esc(url)}" target="_blank" rel="noopener">${esc(url)}</a>`).join('<br>');
}

export async function onRequestGet(context) {
  const origin = new URL(context.request.url).origin;
  const record = await (await fetch(origin + '/api/build-audit')).json();
  const rows = record.truth_board.map(row => `<tr>
    <th><span>${esc(row.label)}</span><code>${esc(row.axis)}</code></th>
    <td><p>${esc(row.field_claim)}</p><div class="sources">${links(row.field_sources)}</div></td>
    <td><p>${esc(row.field_evidence)}</p><div class="sources">${links(row.field_sources)}</div></td>
    <td><p>${esc(row.build_claim)}</p><div class="sources">${links(row.build_sources)}</div></td>
    <td><p>${esc(row.build_evidence)}</p><div class="sources">${links(row.build_sources)}</div></td>
  </tr>`).join('');
  const result = record.current_result;
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Build evidence board</title><style>
*{box-sizing:border-box}body{margin:0;color:#111;background:#fff;font:16px/1.48 system-ui,-apple-system,sans-serif}a{color:#0645ad;text-underline-offset:2px}.wrap{width:min(1500px,calc(100% - 32px));margin:auto}header{padding:58px 0 34px;border-bottom:3px solid #111}.eyebrow{font:800 12px/1.2 system-ui;text-transform:uppercase;letter-spacing:.12em}h1{font-size:clamp(40px,6vw,76px);line-height:.98;letter-spacing:-.05em;margin:14px 0 20px;max-width:1050px}.dek{font:23px/1.4 Georgia,serif;max-width:980px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}button,.button{display:inline-block;padding:11px 15px;border:1px solid #111;background:#fff;color:#111;font-weight:750;text-decoration:none;cursor:pointer}.summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:#bbb;border:1px solid #bbb;margin:34px 0}.summary article{background:#fff;padding:22px}.summary h2{font-size:12px;letter-spacing:.1em;text-transform:uppercase;margin:0 0 9px}.summary p{font-size:19px;margin:0}.failure{grid-column:1/-1;background:#111!important;color:#fff!important}.board{overflow:auto;border:1px solid #999;margin:34px 0}table{border-collapse:collapse;width:100%;min-width:1320px}thead th{position:sticky;top:0;background:#111;color:#fff;text-align:left;padding:14px;font-size:13px;letter-spacing:.04em}tbody th,td{vertical-align:top;text-align:left;border-right:1px solid #bbb;border-bottom:1px solid #bbb;padding:16px}tbody th{width:170px;background:#f1f1f1}tbody th span,tbody th code{display:block}tbody th code{font-size:11px;color:#666;margin-top:8px}td{width:285px}td p{margin:0 0 16px}.sources{border-top:1px solid #ddd;padding-top:10px;font:11px/1.45 ui-monospace,monospace;overflow-wrap:anywhere}.graph{padding:30px 0 60px}.graph ul{line-height:1.9}.status{font-weight:700;margin-top:10px}@media(max-width:720px){.summary{grid-template-columns:1fr}.failure{grid-column:auto}}
</style></head><body><main class="wrap"><header><div class="eyebrow">Four records. One voxel graph. No requested verdict.</div><h1>What this build is. What the field has. What the evidence establishes.</h1><p class="dek">${esc(record.plain_description)}</p><div class="actions"><button id="copy">Copy graph access</button><a class="button" href="/api/build-landscape">Landscape table</a><a class="button" href="/api/build-landscape?next=1">Next research object</a><a class="button" href="/a/opos-formal-audit">Root article</a><a class="button" href="/api/articles/opos-formal-audit/claims">Claim voxels</a><a class="button" href="/api/articles/opos-formal-audit/discourse">Discourse</a></div><div class="status" id="status"></div></header>
<section class="summary"><article><h2>Shared with the field</h2><p>${esc(result.shared_with_field)}</p></article><article><h2>Demonstrated combination</h2><p>${esc(result.demonstrated_combination)}</p></article><article><h2>Uniqueness</h2><p>${esc(result.uniqueness)}</p></article><article><h2>Foremost now</h2><p>${esc(result.foremost_at_now)}</p></article><article><h2>Foremost objective</h2><p>${esc(result.ought_to_be_foremost_at)}</p></article><article class="failure"><h2>Primary failure</h2><p>${esc(result.primary_failure)}</p></article></section>
<section class="board"><table><thead><tr><th>Axis</th><th>What the field says</th><th>What field evidence establishes</th><th>What this build says</th><th>What build evidence establishes</th></tr></thead><tbody>${rows}</tbody></table></section>
<section class="graph"><h2>This table is a view of the article graph</h2><ul><li>Root article: <a href="${esc(record.subject.public_article)}">${esc(record.subject.public_article)}</a></li><li>Claims: <a href="${esc(record.subject.claim_voxels)}">${esc(record.subject.claim_voxels)}</a></li><li>Source ledger: <a href="${origin}/api/articles/opos-formal-audit/sources">${origin}/api/articles/opos-formal-audit/sources</a></li><li>Discourse: <a href="${esc(record.subject.discourse)}">${esc(record.subject.discourse)}</a></li><li>Landscape: <a href="${origin}/api/build-landscape">${origin}/api/build-landscape</a></li></ul><p>Outside-model research enters as fetched, hash-chained source voxels and source-citing claim voxels. Opposition attaches to exact claim hashes. The task table queues work; it is not a second truth store.</p></section></main><script>
document.getElementById('copy').onclick=async()=>{const out=document.getElementById('status');out.textContent='Minting graph research capability…';const res=await fetch('/api/dispatch?tap_go=1&drop=audit');const text=await res.text();if(!res.ok){out.textContent='Copy failed: HTTP '+res.status;return}await navigator.clipboard.writeText(text);out.textContent='Copied graph access record · '+text.length.toLocaleString()+' characters'};
</script></body></html>`;
  return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } });
}
