import { buildCapabilityAtlas } from '../_lib/capability_atlas.js';
import { governanceHeader, governanceFooter, governanceChromeStyles } from '../_lib/governance_chrome.js';

function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

export async function onRequestGet(context) {
  const atlas = await buildCapabilityAtlas(context.env, context.request.url, { includeCapabilities: true });
  const s = atlas.summary;
  const domainHtml = atlas.domains.map(d => `<button class="domain" data-domain="${esc(d.id)}"><strong>${esc(d.name)}</strong><span>${d.registered} registered · ${d.invoked} invoked · ${d.with_registered_tests} with tests · ${d.with_current_test_pass} current pass</span><small>${d.recorded_invocations.toLocaleString()} recorded invocations</small></button>`).join('');
  const agentsHtml = atlas.turn_archaeology.agent_activity.slice(0, 20).map(a => `<tr><td>${esc(a.agent)}</td><td>${Number(a.turns).toLocaleString()}</td><td>${Number(a.sessions).toLocaleString()}</td><td>${Number(a.file_changing_turns).toLocaleString()}</td><td>${esc(a.latest_turn)}</td></tr>`).join('');
  const filesHtml = atlas.turn_archaeology.changed_files.top.slice(0, 30).map(f => `<tr><td><code>${esc(f.file)}</code></td><td>${f.turns.toLocaleString()}</td><td>${esc(f.last_changed)}</td></tr>`).join('');
  const capsJson = JSON.stringify(atlas.capabilities).replace(/</g, '\\u003c');
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Capability Atlas — miscsubjects</title><style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#080808;font:17px/1.55 Georgia,serif}a{color:#000;text-decoration:underline;text-underline-offset:3px}.wrap{width:min(1240px,calc(100% - 32px));margin:auto}.wrap>header{padding:62px 0 38px;border-bottom:4px solid #000}.eyebrow,.label{font:800 12px/1.2 system-ui,sans-serif;text-transform:uppercase;letter-spacing:.12em}h1{font:900 clamp(46px,8vw,96px)/.9 system-ui,sans-serif;letter-spacing:-.06em;margin:18px 0 24px;max-width:1100px}header p{font-size:clamp(20px,2.7vw,30px);line-height:1.32;max-width:920px}.urls{font:14px/1.65 ui-monospace,monospace;overflow-wrap:anywhere}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1px;background:#999;border:1px solid #999;margin:35px 0}.stat{background:#fff;padding:20px}.stat strong{display:block;font:900 34px/1 system-ui,sans-serif}.stat span{font:700 12px/1.3 system-ui,sans-serif;text-transform:uppercase}section{padding:44px 0;border-bottom:1px solid #aaa}h2{font:900 clamp(30px,5vw,54px)/1 system-ui,sans-serif;letter-spacing:-.04em;margin:10px 0 24px}h3{font:800 20px/1.2 system-ui,sans-serif}.domains{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.domain{text-align:left;border:1px solid #888;background:#fff;color:#000;padding:17px;cursor:pointer}.domain strong,.domain span,.domain small{display:block}.domain strong{font:800 16px/1.25 system-ui,sans-serif}.domain span{margin:8px 0;font:13px/1.3 system-ui,sans-serif}.domain small{font:12px/1.3 ui-monospace,monospace}.domain.active{background:#000;color:#fff}.filters{display:grid;grid-template-columns:minmax(240px,2fr) repeat(3,minmax(130px,1fr));gap:10px;position:sticky;top:0;background:#fff;padding:13px 0;z-index:2;border-bottom:2px solid #000}.filters input,.filters select{width:100%;border:1px solid #555;background:#fff;color:#000;padding:12px;font:14px system-ui,sans-serif}.result-count{font:800 13px system-ui,sans-serif;margin:18px 0}.cap-list{display:grid;gap:10px}.cap{border:1px solid #aaa;padding:16px;display:grid;grid-template-columns:minmax(190px,.8fr) minmax(260px,2fr) minmax(190px,.8fr);gap:18px}.cap h3{margin:0 0 8px;overflow-wrap:anywhere}.cap p{margin:0}.meta,.proof{font:12px/1.5 system-ui,sans-serif}.badge{display:inline-block;border:1px solid #222;padding:3px 6px;margin:0 4px 5px 0;font:800 10px/1 system-ui,sans-serif;text-transform:uppercase}.proof strong{font-size:24px}.proof a{display:block;margin-top:6px}.scroll{overflow:auto;border:1px solid #aaa}table{border-collapse:collapse;width:100%;min-width:760px;font:13px/1.4 system-ui,sans-serif}th,td{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #ccc}th{background:#eee}code{font:12px ui-monospace,monospace}.boundary{background:#000;color:#fff;padding:20px}.boundary li{margin:8px 0}@media(max-width:780px){.filters{grid-template-columns:1fr 1fr}.filters input{grid-column:1/-1}.cap{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr}}
${governanceChromeStyles()}</style></head><body>${governanceHeader('governance')}<main class="wrap"><header><div class="eyebrow">Live capability archaeology · ${esc(atlas.schema)}</div><h1>What the build can actually do</h1><p>This atlas reconstructs the capability mass beneath the visible product: current contracts, recorded use, tests, and the coding-agent turns that accumulated it.</p><div class="urls">${esc(atlas.urls.full_json)}<br>${esc(atlas.urls.formal_audit_drop)}</div><div class="stats"><div class="stat"><strong>${s.registered_capabilities.toLocaleString()}</strong><span>registered capability objects</span></div><div class="stat"><strong>${s.enabled_capabilities.toLocaleString()}</strong><span>enabled now</span></div><div class="stat"><strong>${s.capabilities_with_recorded_invocations.toLocaleString()}</strong><span>with recorded invocation</span></div><div class="stat"><strong>${s.recorded_invocations_across_current_capabilities.toLocaleString()}</strong><span>recorded invocations</span></div><div class="stat"><strong>${Number(atlas.turn_archaeology.summary.total || 0).toLocaleString()}</strong><span>coding-agent turns</span></div><div class="stat"><strong>${Number(atlas.turn_archaeology.summary.file_changing_turns || 0).toLocaleString()}</strong><span>file-changing turns</span></div></div></header>
<section><div class="label">Capability domains</div><h2>The buried system, grouped</h2><div class="domains">${domainHtml}</div></section>
<section><div class="label">Full current registry</div><h2>Search every capability object</h2><div class="filters"><input id="search" type="search" placeholder="Search key, category, description, or domain"><select id="domain"><option value="">All domains</option>${atlas.domains.map(d => `<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select><select id="type"><option value="">All types</option><option>fn</option><option>http</option><option>agent</option><option>flow</option></select><select id="verification"><option value="">All evidence states</option><option value="tested_and_invoked">Tested and invoked</option><option value="tested">Tested</option><option value="invoked_not_test_proven">Invoked, not test-proven</option><option value="test_exists_not_currently_passed">Test exists, not passed</option><option value="registered_only">Registered only</option><option value="disabled">Disabled</option></select></div><div class="result-count" id="count"></div><div class="cap-list" id="caps"></div></section>
<section><div class="label">Accumulation evidence</div><h2>Thousands of coding-agent turns</h2><p>${Number(atlas.turn_archaeology.summary.total || 0).toLocaleString()} durable turns across ${Number(atlas.turn_archaeology.summary.sessions || 0).toLocaleString()} sessions and ${Number(atlas.turn_archaeology.summary.agents || 0).toLocaleString()} agent labels. Raw owner prompts remain private; this page exposes aggregates and sanitized changed-file paths.</p><h3>Agent activity</h3><div class="scroll"><table><thead><tr><th>Agent</th><th>Turns</th><th>Sessions</th><th>File-changing</th><th>Latest</th></tr></thead><tbody>${agentsHtml}</tbody></table></div><h3>Most repeatedly changed implementation surfaces</h3><div class="scroll"><table><thead><tr><th>File</th><th>Turns changing it</th><th>Latest change</th></tr></thead><tbody>${filesHtml}</tbody></table></div></section>
<section><div class="label">Evidence law</div><h2>What these numbers do and do not prove</h2><ul class="boundary">${atlas.evidence_boundaries.map(x => `<li>${esc(x)}</li>`).join('')}</ul></section></main><script>
const capabilities=${capsJson};const search=document.getElementById('search'),domain=document.getElementById('domain'),type=document.getElementById('type'),verification=document.getElementById('verification'),caps=document.getElementById('caps'),count=document.getElementById('count');
function e(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function render(){const q=search.value.trim().toLowerCase();const found=capabilities.filter(c=>(!q||c.search_text.includes(q))&&(!domain.value||c.domain===domain.value)&&(!type.value||c.type===type.value)&&(!verification.value||c.evidence.verification===verification.value));count.textContent=found.length.toLocaleString()+' of '+capabilities.length.toLocaleString()+' capability objects';caps.innerHTML=found.slice(0,300).map(c=>'<article class="cap"><div><h3>'+e(c.key)+'</h3><span class="badge">'+e(c.type)+'</span><span class="badge">'+e(c.domain)+'</span><span class="badge">'+e(c.evidence.verification)+'</span><div class="meta">'+e(c.category)+' · '+e(c.target_kind)+(c.sensitive?' · sensitive':'')+'</div></div><p>'+e(c.description)+'</p><div class="proof"><strong>'+Number(c.evidence.recorded_invocations).toLocaleString()+'</strong> recorded invocations<br>'+Number(c.evidence.registered_tests).toLocaleString()+' tests · '+Number(c.evidence.currently_passed_tests).toLocaleString()+' currently passed<a href="'+e(c.urls.human)+'">Open capability page</a><a href="'+e(c.urls.contract)+'">Open machine contract</a></div></article>').join('')+(found.length>300?'<p>Showing first 300. Narrow the filters to inspect the rest.</p>':'')}
[search,domain,type,verification].forEach(x=>x.addEventListener('input',render));document.querySelectorAll('[data-domain]').forEach(b=>b.onclick=()=>{domain.value=domain.value===b.dataset.domain?'':b.dataset.domain;document.querySelectorAll('[data-domain]').forEach(x=>x.classList.toggle('active',x.dataset.domain===domain.value));render();document.getElementById('search').scrollIntoView({behavior:'smooth'})});render();
</script>${governanceFooter()}</body></html>`;
  return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } });
}
