INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('D1_QUERY', 'fn', 'd1Query', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('D1_EXEC', 'fn', 'd1Exec', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('KV_GET', 'fn', 'kvGet', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('KV_PUT', 'fn', 'kvPut', '', '["$1","$2"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('KV_DEL', 'fn', 'kvDel', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('SHA256_LOWER', 'fn', 'sha256Lower', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('NOW', 'fn', 'now', '', '[]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('UPPER', 'fn', 'upper', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('LOWER', 'fn', 'lower', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('DEDUP_INSERT', 'fn', 'dedupInsert', '', '["$1"]', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('BLOOIO_SEND', 'http', 'POST https://backend.blooio.com/v2/api/chats/$1/messages', 'bearer:BLOOIO_API_KEY', '{"text":"$2"}', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('META_CAPI_POST', 'http', 'POST https://graph.facebook.com/v22.0/27209526152071970/events', 'query:access_token=META_CAPI_TOKEN', '{"data":[{"event_name":"$1","event_time":$2,"event_id":"$3","event_source_url":"$4","action_source":"website","user_data":{"client_ip_address":"$5","client_user_agent":"$6"}}]}', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('XAI_CHAT', 'agent', 'grok-build-0.1', 'bearer:GROK_API_KEY', 'You are a helpful assistant.', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('GROK_AUDIT', 'agent', 'grok-build-0.1', 'bearer:GROK_API_KEY', 'You are an audit gate for runtime content changes. You receive a CURRENT value and a PROPOSED value plus optional context. Output strict JSON only, no prose. Shape: {"verdict":"approve"|"reject"|"review","reasons":[string],"diff_summary":string}. approve = safe, on-spec, no regressions. reject = breaks contract, leaks secrets, or contradicts the stated context. review = ambiguous, needs human. Be literal. Do not paraphrase. Do not add fields.', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('ROUTER', 'agent', 'grok-build-0.1', 'bearer:GROK_API_KEY', 'You are a router. Available tools:
{{TOOLS}}
Emit one or more [KEY]body[/KEY] tags to dispatch. Use | to separate args inside body. End with [DONE]<one-line reason>[/DONE] when finished.', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('PAGES_LIST', 'flow', '', '', 'D1_QUERY: SELECT slug, title, version, updated_at FROM pages ORDER BY slug', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('PAGES_GET', 'flow', '', '', 'D1_QUERY: SELECT slug, title, body_html, version, updated_at FROM pages WHERE slug=''$1''', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('PAGES_VERSIONS', 'flow', '', '', 'D1_QUERY: SELECT id, slug, version, title, created_at, actor, length(body_html) AS size_bytes FROM pages_versions WHERE slug=''$1'' ORDER BY version DESC', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('SETTINGS_LIST', 'flow', '', '', 'D1_QUERY: SELECT key, value, description, updated_at FROM settings ORDER BY key', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('SETTINGS_GET', 'flow', '', '', 'D1_QUERY: SELECT key, value, description, updated_at FROM settings WHERE key=''$1''', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('GROK_LEDGER_TAIL', 'flow', '', '', 'D1_QUERY: SELECT id, timestamp, source FROM grok_ledger ORDER BY id DESC LIMIT 20', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('BLOOIO_LOGS_TAIL', 'flow', '', '', 'D1_QUERY: SELECT id, timestamp, direction FROM blooio_logs ORDER BY id DESC LIMIT 20', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('DIRECTORY_LIST', 'flow', '', '', 'D1_QUERY: SELECT key, type, target, updated_at FROM directory ORDER BY key', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('LOG_TAIL', 'flow', '', '', 'D1_QUERY: SELECT id, ts, trace, step, parent, key, type FROM log ORDER BY id DESC LIMIT 50', '2026-06-05T14:00:00Z');
INSERT OR REPLACE INTO directory (key, type, target, auth, content, updated_at) VALUES ('SERVE_PAGE', 'flow', '', '', 'D1_QUERY: SELECT body_html FROM pages WHERE slug=''$1''', '2026-06-05T14:00:00Z');
