INSERT INTO tasks (created_at, status, body, source, trace) VALUES
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"x-terminal-key auth mismatch returns 401 on /api/dispatch and mutating /api/tasks when key casing differs from env.TERMINAL_KEY.","impact":"blocks live DB mutations and cron runners","status":"observed"}', 'audit', 'functions/api/dispatch.js:2644'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"DONETASK directory row was missing; agents could not close tasks via dispatch.","impact":"task queue could not be drained by agents","status":"fixed by migration 0127"}', 'audit', 'functions/api/dispatch.js'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"TASKS_ADD flow row omitted created_at and stored plain text instead of a structured JSON job.","impact":"broken row + cron runner could not parse job fields","status":"fixed by migrations 0116/0127"}', 'audit', 'migrations/0116_laws_directory_rows.sql'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"~100 stale source=pepper open tasks were clogging the queue, hiding real writer jobs.","impact":"GET /api/tasks/next?role=writer returned null","status":"fixed by migration 0128"}', 'audit', 'tasks table backlog'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"taskRunNext fed the raw task body to ROUTER and ignored role/model/ask/post_to fields.","impact":"structured jobs never executed","status":"fixed in functions/api/dispatch.js"}', 'audit', 'functions/api/dispatch.js:taskRunNext'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"GET /api/protocol/next returns the next open task but does not claim it (status stays open).","impact":"cron could pull the same task repeatedly","status":"open"}', 'audit', 'functions/api/protocol/[[path]].js:next'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"POST /api/protocol/score is not implemented; adversary/endorsement reviews do not affect claim weights.","impact":"model teams cannot score or gate content","status":"open"}', 'audit', 'PROTOCOL_SPEC.md §5 / task 156'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"POST /api/protocol/inventory and POST /api/protocol/outline endpoints are not implemented.","impact":"P0/P1 protocol phases cannot run","status":"open"}', 'audit', 'PROTOCOL_SPEC.md §5 / task 160'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"P8 materiality/rest gate is not implemented; non-material contributions are not rejected and energy is not logged.","impact":"wasted model runs are not tracked","status":"open"}', 'audit', 'PROTOCOL_SPEC.md §2 / task 157'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"pipelineSeed historically stored peptide names as [object Object]; combinatorial mapping REST endpoint is missing.","impact":"pipeline names are dirty and combinatorial pages cannot be driven","status":"open"}', 'audit', 'functions/api/dispatch.js:pipelineSeed / task 164'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"Google Tasks sync in taskAdd/tasksSyncGoogle silently swallows all errors.","impact":"sync failures are invisible in the ledger","status":"open"}', 'audit', 'functions/api/dispatch.js:taskAdd / tasksSyncGoogle'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"Source ledger hash body (srcBody) omits author, publisher, and date fields.","impact":"those fields are not integrity-protected by the chain","status":"open"}', 'audit', 'functions/api/protocol/[[path]].js:srcBody'),
(datetime('now'), 'logged', '{"role":"audit","category":"failure","description":"Claim evidence_basis field is documented but not enforced in draft().","impact":"law A4/N2 unenforced; claim provenance unclear","status":"open"}', 'audit', 'functions/api/protocol/[[path]].js:draft');
