-- 0131: Log MCP / GitHub audit failure modes into the Tasks API shared ledger.
INSERT INTO tasks (created_at, status, body, source, trace) VALUES
(datetime('now'), 'logged', '{"role":"audit","category":"mcp","description":"Cloudflare MCP build-direct import is blocked: OAuth tokens are audience-bound to /sse, and /mcp requires Mcp-Session-Id stateful sessions which mcpRpc does not implement.","impact":"14 seeded Cloudflare MCP servers remain unusable build-direct","status":"open"}', 'audit', 'functions/api/dispatch.js:mcpRpc / MCP_INVENTORY_AND_AUDIT.md §5.2.A'),
(datetime('now'), 'logged', '{"role":"audit","category":"mcp","description":"GitHub MCP server is seeded but not imported as native directory rows; agents still rely on hand-rolled GH_* HTTP rows.","impact":"native GitHub MCP tools (issues/PRs/etc) unavailable build-direct","status":"open"}', 'audit', 'migrations/0123_mcp_oauth_controls.sql / MCP_INVENTORY_AND_AUDIT.md §5.2'),
(datetime('now'), 'logged', '{"role":"audit","category":"mcp","description":"MCP_AGENT prompt claims 14 Cloudflare MCP tools are attached via xAI, but MCP_AGENT_mcp and mcp_attach KV values are cleared.","impact":"agent will hallucinate tool calls","status":"open"}', 'audit', 'migrations/0124_whitelist_and_mcp_agent_selfedit.sql'),
(datetime('now'), 'logged', '{"role":"audit","category":"mcp","description":"MCP_SPEC.md / MCP_SPEC.json are stale relative to the live seeded-but-dormant state documented in MCP_INVENTORY_AND_AUDIT.md.","impact":"docs misrepresent what is wired","status":"open"}', 'audit', 'MCP_SPEC.md / MCP_SPEC.json'),
(datetime('now'), 'logged', '{"role":"audit","category":"mcp","description":"Old MCP row from migration 0049/0058 still references agent.cannibal.capital and the grok mcp CLI; it is obsolete.","impact":"confusing dead row in directory","status":"open"}', 'audit', 'migrations/0049_terminal_annex_catalog.sql / 0058_consolidation.sql'),
(datetime('now'), 'logged', '{"role":"audit","category":"mcp","description":"xAI-inject MCP path is dormant but code remains active; any KV_PUT to mcp_attach or <KEY>_mcp will re-enable it.","impact":"risk of accidental re-enable","status":"open"}', 'audit', 'functions/api/dispatch.js:dispatch / mcpToolsForAgent'),
(datetime('now'), 'logged', '{"role":"audit","category":"mcp","description":"mcpToolCall returns flat text instead of structured JSON, losing isError flag and nested result objects.","impact":"dispatch agent sees wall of text instead of typed results","status":"open"}', 'audit', 'functions/api/dispatch.js:mcpToolCall');
