
CREATE TABLE IF NOT EXISTS model_index_sources (
  id               TEXT PRIMARY KEY,      -- slug: 'openrouter-models-api'
  name             TEXT NOT NULL,
  url              TEXT NOT NULL,         -- the human page
  machine_endpoint TEXT,                  -- verified JSON/API/llms.txt path, if one exists
  lane             TEXT NOT NULL,         -- capability | price | usage | practice | trends
  what_it_answers  TEXT NOT NULL,         -- one plain sentence
  cadence          TEXT,                  -- live | daily | weekly | per_release | annual | static
  evidence_class   TEXT,                  -- first_party_api | benchmark | aggregator | lab_blog | paper_feed | press
  why_definitive   TEXT,                  -- one falsifiable sentence
  access           TEXT,                  -- free | key | paid
  verified_at      TEXT,                  -- last time this build fetched it successfully
  verified_status  INTEGER,               -- HTTP status at last verification
  added_at         TEXT NOT NULL,
  retired_at       TEXT,
  retired_reason   TEXT
);

CREATE INDEX IF NOT EXISTS idx_mis_lane ON model_index_sources (lane, retired_at);
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('artificial-analysis','Artificial Analysis','https://artificialanalysis.ai/','https://artificialanalysis.ai/api/v2/data/llms/models','capability','Independent, standardized quality-versus-price-versus-speed comparison of every major model across every major provider.','daily','benchmark','It runs its own harness against live provider endpoints and publishes the methodology, so its numbers are measured, not vendor-quoted.','key','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('arena-lmarena','Arena (formerly LMArena)','https://arena.ai/leaderboard',NULL,'capability','Which models real humans prefer in blind head-to-head battles, as an Elo ranking.','live','benchmark','Millions of crowdsourced blind pairwise votes make it the largest human-preference signal that cannot be gamed by training on a fixed test set.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('swe-bench','SWE-bench','https://www.swebench.com/','https://github.com/swe-bench/experiments','capability','How well models and agent scaffolds resolve real GitHub issues in real repositories, graded by running the repository tests.','per_release','benchmark','The de facto standard coding-agent benchmark; leaderboard entries require submitted, reproducible trajectories.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('terminal-bench','Terminal-Bench','https://www.tbench.ai/leaderboard',NULL,'capability','How model-plus-harness combinations perform on end-to-end tasks in a real terminal environment.','per_release','benchmark','The only public leaderboard that scores the model and the harness as a pair, which isolates the harness effect on agentic work.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('aider-polyglot','Aider Polyglot Leaderboard','https://aider.chat/docs/leaderboards/','https://github.com/Aider-AI/aider','capability','Code-editing accuracy and cost per run across 225 hard exercises in six languages, including edit-format compliance.','per_release','benchmark','Run by a shipping open-source tool against its own production edit formats, with per-run dollar cost published next to every score.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('livebench','LiveBench','https://livebench.ai/','https://huggingface.co/livebench','capability','Contamination-resistant general capability scores from questions refreshed monthly with objective ground-truth grading.','per_release','benchmark','Monthly-refreshed questions and objective scoring make it the standard control for test-set contamination claims.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('eq-bench','EQ-Bench','https://eqbench.com/',NULL,'capability','Writing quality, emotional intelligence, and sycophancy (Spiral-Bench) rankings the big benchmarks do not measure.','per_release','benchmark','The only maintained leaderboard family with published methodology for writing and sycophancy, dimensions absent from every coding suite.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('ifbench-ai2','IFBench (Ai2)','https://github.com/allenai/IFBench','https://arxiv.org/abs/2507.02833','capability','Precise instruction-following on new, unseen, machine-verifiable output constraints.','static','benchmark','Ai2-built with programmatically verifiable constraints, so scores are checkable by re-running the released code rather than trusting a judge model.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('llm-stats','llm-stats.com','https://llm-stats.com/',NULL,'capability','One-page cross-reference of context windows, prices, and headline benchmark scores for fast model triage.','daily','aggregator','The fastest single lookup table joining specs, price and scores; each cell traceable to a first-party number.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('epoch-ai','Epoch AI Data Hub','https://epoch.ai/data','https://epoch.ai/data/all_ai_models.csv','capability','Documented data on model compute, training costs, capability trends, and independently re-run benchmark results.','weekly','benchmark','Every datapoint carries a documented estimation method, and its Benchmarking Hub re-runs evaluations itself instead of copying lab claims.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('metr','METR Evaluations','https://metr.org/evaluations/',NULL,'capability','Independent measurements of frontier-model autonomous-task time horizons and dangerous-capability evaluations.','per_release','benchmark','METR gets pre-release access from the labs and publishes the time-horizon doubling curve that has become the standard measure of agentic capability growth.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('helm-stanford','HELM (Stanford CRFM)','https://crfm.stanford.edu/helm/','https://github.com/stanford-crfm/helm','capability','Fully transparent multi-scenario evaluations where every prompt and completion is inspectable.','per_release','benchmark','Unique in publishing every raw prompt and completion pair, making any score independently auditable.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('openrouter-models-api','OpenRouter Models API','https://openrouter.ai/models','https://openrouter.ai/api/v1/models','price','Machine-readable current price, context window, and modality for every model OpenRouter routes.','live','first_party_api','These are transactable prices OpenRouter actually bills at, updated the moment a provider changes them.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('openrouter-endpoints-api','OpenRouter Per-Endpoint Pricing API','https://openrouter.ai/docs','https://openrouter.ai/api/v1/models/{author}/{slug}/endpoints','price','Provider-by-provider price, quantization, uptime, and throughput for a single model.','live','first_party_api','The only public endpoint exposing that the same open-weight model sells at different prices and precisions across hosts.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('anthropic-pricing','Anthropic Pricing Docs','https://platform.claude.com/docs/en/about-claude/pricing','https://platform.claude.com/llms.txt','price','First-party per-token prices, cache pricing, and batch discounts for every current Claude model.','per_release','first_party_api','The billing source of truth for Claude, with an llms.txt so a model can pull exact current numbers without scraping.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('openai-pricing','OpenAI Pricing Docs','https://developers.openai.com/api/docs/pricing','https://developers.openai.com/llms.txt','price','First-party per-token, cached-input, batch, and tool pricing for every OpenAI API model.','per_release','first_party_api','The developer-docs pricing table is what OpenAI bills against, and the domain serves llms.txt for machine refresh.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('deepseek-pricing','DeepSeek Pricing Docs','https://api-docs.deepseek.com/quick_start/pricing/','https://api-docs.deepseek.com/llms.txt','price','First-party token prices including cache-hit against cache-miss rates and the peak-hour doubling window.','per_release','first_party_api','DeepSeek sets the market''s low-cost benchmark and only this page carries the exact current numbers, including the time-of-day multiplier.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('gemini-pricing','Google Gemini API Pricing','https://ai.google.dev/gemini-api/docs/pricing','https://ai.google.dev/gemini-api/docs/llms.txt','price','First-party per-token prices for all Gemini API models including the long-context price tiers.','per_release','first_party_api','The billing source of truth for Gemini, including the context-length price breakpoints aggregators frequently get wrong.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('cloudflare-workers-ai-pricing','Cloudflare Workers AI Pricing','https://developers.cloudflare.com/workers-ai/platform/pricing/','https://developers.cloudflare.com/llms.txt','price','Per-model unit pricing for models served on Cloudflare''s own inference.','per_release','first_party_api','The first-party billing table for edge-hosted open models, with a full-site llms.txt for automated refresh.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('cloudflare-ai-gateway-pricing','Cloudflare AI Gateway Pricing','https://developers.cloudflare.com/ai-gateway/reference/pricing/','https://developers.cloudflare.com/llms.txt','price','What the gateway costs when routing any provider through Cloudflare: pass-through tokens, the unified-billing fee, log storage.','per_release','first_party_api','The first-party statement needed to compute true all-in cost per token when proxying providers.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('aws-bedrock-pricing','AWS Bedrock Pricing','https://aws.amazon.com/bedrock/pricing/','https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonBedrock/current/index.json','price','Enterprise-channel prices for hosted frontier and open models on Bedrock, including batch and provisioned throughput.','per_release','first_party_api','The Price List JSON is the same feed AWS billing runs on — the only fully machine-readable first-party enterprise price source.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('litellm-prices-json','LiteLLM model prices JSON','https://github.com/BerriAI/litellm','https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json','price','One JSON file mapping virtually every model id on every provider to price, context window, and feature flags.','live','aggregator','It is the cost table inside LiteLLM''s production billing code, so thousands of deployments file corrections the day a price changes.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('helicone-llm-costs','Helicone LLM Cost API','https://www.helicone.ai/llm-cost','https://www.helicone.ai/api/llm-costs','price','A queryable keyless JSON cost lookup by model name, as a cross-check against LiteLLM.','live','aggregator','Backed by the cost-calculation package Helicone uses to bill real proxied traffic, and callable without auth.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('openrouter-rankings','OpenRouter Rankings','https://openrouter.ai/rankings',NULL,'usage','Which models developers actually spend tokens on, by real routed volume, sliceable by use case.','live','aggregator','Revealed preference from trillions of actually-billed tokens — the closest public proxy to market share that cannot be astroturfed.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('openrouter-state-of-ai','OpenRouter State of AI','https://openrouter.ai/state-of-ai',NULL,'usage','Longitudinal analysis of usage shifts across labs, open against closed weights, and use-case mix from OpenRouter''s own traffic.','per_release','aggregator','The only published longitudinal usage study built on metered production traffic rather than surveys.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('anthropic-engineering','Anthropic Engineering Blog','https://www.anthropic.com/engineering',NULL,'practice','Canonical agent and harness practice: building effective agents, context engineering, multi-agent systems, Claude Code internals.','weekly','lab_blog','The most-cited harness-design documents in the field, written by the lab that ships Claude Code.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('openai-cookbook','OpenAI Cookbook','https://developers.openai.com/cookbook','https://github.com/openai/openai-cookbook','practice','Runnable first-party reference implementations for tool use, agents, RAG, evals, and orchestration.','weekly','lab_blog','Every pattern ships as executable code maintained by the vendor, so guidance is testable rather than rhetorical.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('deepmind-blog','Google DeepMind Blog','https://deepmind.google/blog/',NULL,'practice','First-party announcements and research posts for Gemini releases and DeepMind research directions.','weekly','lab_blog','The primary source for Gemini capability claims and release timing.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('manus-context-engineering','Manus: Context Engineering for AI Agents','https://manus.im/blog/Context-Engineering-for-AI-Agents-Lessons-from-Building-Manus',NULL,'practice','Production lessons on KV-cache economics, tool-set stability, file-as-memory, and error retention in a shipping general agent.','static','lab_blog','The most-referenced single practitioner document on context engineering, written from four complete rebuilds of a production agent.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('cursor-blog','Cursor Blog','https://cursor.com/blog',NULL,'practice','Engineering posts from the highest-volume AI coding product on harness design and large-scale agent telemetry.','weekly','lab_blog','Cursor operates one of the largest coding-agent fleets in production, so its posts report measured behavior at scale rather than demos.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('langchain-state-of-agents','LangChain Blog / State of AI Agents','https://www.langchain.com/blog',NULL,'practice','Framework-side agent engineering plus the recurring State of AI Agents survey of thousands of practitioners.','weekly','aggregator','The State of AI Agents reports are the largest published practitioner surveys on what agent architectures teams actually deploy.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('hamel-evals','Hamel Husain — LLM Evals','https://hamel.dev/blog/posts/evals/',NULL,'practice','The standard practitioner methodology for building eval suites: error analysis, judge validation, eval-driven iteration.','static','lab_blog','The most-cited applied evals methodology, built from documented client engagements rather than theory.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('anthropic-system-cards','Anthropic System Cards (Transparency Hub)','https://www.anthropic.com/transparency',NULL,'practice','First-party capability, safety-evaluation, and behavioral documentation for each Claude model at release.','per_release','lab_blog','System cards contain the pre-deployment evaluation numbers and known-behavior disclosures no third party can produce.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('openai-system-cards','OpenAI Deployment Safety Hub','https://deploymentsafety.openai.com/',NULL,'practice','Index of OpenAI system cards and safety documentation for each deployed model.','per_release','lab_blog','The only consolidated first-party index of OpenAI''s pre-deployment evaluations that is fetchable by automated agents.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('arxiv-cs-ai','arXiv cs.AI Recent','https://arxiv.org/list/cs.AI/recent','https://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending','trends','Every new AI paper the moment it is posted, before any curation layer.','daily','paper_feed','The primary preprint firehose — all downstream trend detection derives from this feed.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('arxiv-cs-cl','arXiv cs.CL Recent','https://arxiv.org/list/cs.CL/recent','https://export.arxiv.org/api/query?search_query=cat:cs.CL&sortBy=submittedDate&sortOrder=descending','trends','Every new language-model paper as posted, where most LLM methods work first appears.','daily','paper_feed','cs.CL is the home category for LLM research; monitoring it catches methods papers days before blogs cover them.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('hf-daily-papers','Hugging Face Daily Papers','https://huggingface.co/papers','https://huggingface.co/api/daily_papers','trends','Community-upvoted ranking of which new papers practitioners actually consider important each day.','daily','paper_feed','The upvote layer from working ML engineers is the best same-day filter on the arXiv firehose, and it ships a free JSON API.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('hn-algolia','Hacker News (Algolia API)','https://hn.algolia.com/','https://hn.algolia.com/api/v1/search?query=llm&tags=story','trends','Real-time practitioner reaction, criticism, and discovered edge cases for every model release and AI tool.','live','aggregator','Launch claims get independently stress-tested in these threads first, and the full corpus is queryable via a free stable JSON API.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('simon-willison','Simon Willison''s Weblog','https://simonwillison.net/','https://simonwillison.net/atom/everything/','trends','Same-day independent hands-on testing of every significant model release.','daily','press','He personally re-runs vendor claims within hours of release, making it the fastest independent verification layer in the field.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('latent-space','Latent Space','https://www.latent.space/','https://www.latent.space/feed','trends','Long-form interviews with the engineers who build the frontier models and agent harnesses.','weekly','press','Primary-source interviews where roadmap and engineering detail is stated on the record by the builders themselves.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('stanford-ai-index','Stanford AI Index','https://hai.stanford.edu/ai-index',NULL,'trends','Annual cross-checked macro data on AI investment, adoption, benchmark progress, and policy.','annual','aggregator','The most-cited neutral annual baseline; its methodology and raw data are published, so every figure is checkable.','free','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
INSERT OR IGNORE INTO model_index_sources (id,name,url,machine_endpoint,lane,what_it_answers,cadence,evidence_class,why_definitive,access,verified_at,verified_status,added_at) VALUES ('semianalysis','SemiAnalysis','https://semianalysis.com/',NULL,'trends','Compute-supply-side ground truth: accelerator economics, datacenter buildouts, and the cost structures behind model pricing.','weekly','press','Its supply-chain-sourced cost models are the reference numbers labs and investors argue against.','paid','2026-08-05T06:00:00.000Z',200,'2026-08-05T06:00:00.000Z');
