-- 0357 — THE SKILL EVIDENCE GRAPH, storage layer (SPEC_SKILL_EVIDENCE_GRAPH.md, Phases 1, 1.5, 2).
--
-- THE DEFECT THIS CURES. A skill on this build is a build-time JS constant
-- (functions/_lib/skill_registry.js, regenerated by hand). It has no version, no hash, no history:
-- it cannot be cited by version, cannot be hash-bound to a receipt or a work action, and cannot be
-- criticized the way an article version can (content_block_comments pins to (block_id, version,
-- content_hash); nothing equivalent exists for a method). The same defect exists one layer down:
-- directory rows overwrite `content` in place, so a receipt naming object_id cannot prove which
-- contract text it ran under. And one layer up: evidence exists (events, invocations, agent_turns,
-- work_actions) but nothing binds one unit of work into a single manifest another agent can read,
-- grade, or replay.
--
-- Shapes copied deliberately from migrations 0350-0352 (recursive content): append-only version
-- tables keyed (name, version) with a content_hash, and version-pinned comments. Same house
-- pattern, new subject.

-- Phase 1: skills as stored, versioned, hashed objects.
CREATE TABLE IF NOT EXISTS skill_objects (
  name            TEXT PRIMARY KEY,           -- the skill's identity, e.g. 'coding-law'
  family          TEXT,
  license         TEXT,
  source          TEXT,                       -- origin attribution, e.g. 'anthropics/skills'
  current_version INTEGER NOT NULL DEFAULT 1, -- moves only through the promotion path
  retired_at      TEXT,                       -- never deleted; retirement is a recorded state
  created_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skill_versions (
  name           TEXT NOT NULL,
  version        INTEGER NOT NULL,
  content        TEXT NOT NULL,               -- the full SKILL.md text of this version
  content_hash   TEXT NOT NULL,               -- sha256(content); receipts and actions cite this
  parent_version INTEGER,                     -- lineage; NULL for a first version
  change_reason  TEXT NOT NULL,               -- e.g. 'repo sync <commit>', 'failure WF-0012'
  formation_json TEXT,                        -- {failure, work_examples[], proposed_by, forked_from}
  actor          TEXT NOT NULL,
  fingerprint    TEXT,                        -- cap_… of the writing capability, when one was used
  ts             TEXT NOT NULL,
  PRIMARY KEY (name, version)
);

-- Version-pinned criticism of a method — the content_block_comments shape, subject changed.
CREATE TABLE IF NOT EXISTS skill_version_comments (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  name         TEXT NOT NULL,
  version      INTEGER NOT NULL,
  content_hash TEXT NOT NULL,                 -- the exact text the comment was signed against
  stance       TEXT NOT NULL CHECK (stance IN ('question','objection','counterexample','method_proposal','attestation','note')),
  body         TEXT NOT NULL,
  actor        TEXT NOT NULL,
  actor_kind   TEXT NOT NULL DEFAULT 'model' CHECK (actor_kind IN ('model','build','human')),
  fingerprint  TEXT,
  status       TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','answered','superseded')),
  ts           TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_skill_version_comments_name ON skill_version_comments (name, version);

-- Phase 1.5: directory contract versioning. Append-only record of every contract text a
-- capability row has carried, so an invocation can be pinned to the contract it actually ran under.
CREATE TABLE IF NOT EXISTS directory_versions (
  key          TEXT NOT NULL,
  version      INTEGER NOT NULL,
  content      TEXT NOT NULL,                 -- the row's contract text at this version
  content_hash TEXT NOT NULL,
  actor        TEXT,
  ts           TEXT NOT NULL,
  PRIMARY KEY (key, version)
);

-- Phase 2: the execution-evidence manifest. A manifest, not a ledger — every entry in
-- manifest_json is a reference (id + hash) into work_actions, invocations, events or agent_turns.
-- verify recomputes every referenced hash; a manifest that references a record that does not
-- resolve is invalid, which is what upgrades "PARTIAL is honest" into "complete is checkable".
CREATE TABLE IF NOT EXISTS work_evidence (
  task_id       TEXT NOT NULL,
  revision      INTEGER NOT NULL DEFAULT 1,   -- a re-assembly appends, never overwrites
  manifest_json TEXT NOT NULL,                -- schema oip/work-evidence/1 (see functions/_lib/work_evidence.js)
  manifest_hash TEXT NOT NULL,                -- sha256(manifest_json); what reproductions cite
  synthesized   INTEGER NOT NULL DEFAULT 0,   -- 1 = assembled after the fact, not at submit time
  -- DISCLOSURE IS INFRASTRUCTURE, NOT PROSE (spec: evidence pools). What a reader may see is a
  -- column the route enforces, never a policy paragraph:
  --   public    — manifest and resolved payloads are keylessly readable
  --   hash_only — existence, hashes and the verify verdict are public; step payloads are not
  --   private   — reads require a capability; the row still exists and still verifies
  -- ('pool' joins this vocabulary when evidence pools exist; a value the route does not know
  --  is treated as private, never as public.)
  disclosure    TEXT NOT NULL DEFAULT 'public' CHECK (disclosure IN ('public','hash_only','private')),
  actor         TEXT,
  created_at    TEXT NOT NULL,
  PRIMARY KEY (task_id, revision)
);
