// /admin/traffic-console — the growth console: one surface over the traffic engine (/api/traffic)
// and the canonical growth graph (/api/growth). Every panel is a live query. Optimize calls the
// winner per arm; Media is the ad graph with derived CTR/CPC/CPA/ROAS from primitives; Journey is one
// person end to end; Providers is the capability matrix; Proposals is the action queue (nothing here
// executes a proposal). Data / Split / Simulate / Rules / Versions / Lists act on the engine.

import { shellHtml } from './_layout.js';

const BODY = `
<style>
.tc-tabs{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 16px}.tc-tabs button{background:#fff;border:1px solid var(--line);border-radius:8px;padding:9px 14px;cursor:pointer;font-weight:600;font-size:13px}.tc-tabs button.on{background:var(--ink);color:#fff;border-color:var(--ink)}
.tc-panel{display:none}.tc-panel.on{display:block}.tc-card{border:1px solid var(--line);border-radius:10px;background:#fff;padding:16px;margin:0 0 14px}.tc-card h3{margin:0 0 10px;font-size:14px}
.tc-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:0 0 10px}.tc-row input,.tc-row select,.tc-full input{width:100%;padding:8px;border:1px solid var(--line);border-radius:7px;font-size:13px}.tc-full{margin:0 0 10px}
textarea{width:100%;min-height:60px;padding:10px;border:1px solid var(--line);border-radius:8px;font:13px var(--mono);resize:vertical}
button.go{background:var(--ink);color:#fff;border:0;border-radius:8px;padding:10px 16px;font-weight:600;cursor:pointer}button.ghost{background:#fff;border:1px solid var(--line);border-radius:8px;padding:8px 12px;cursor:pointer;font-size:12px}
.grid-wrap{overflow:auto;border:1px solid var(--line);border-radius:8px;background:#fff;max-height:74vh}table.grid{border-collapse:collapse;font-size:11px;white-space:nowrap}table.grid th,table.grid td{text-align:left;padding:5px 8px;border-bottom:1px solid var(--line);border-right:1px solid #f0eee8}table.grid thead th{position:sticky;top:0;background:#faf9f6;z-index:2;font-size:10px;text-transform:uppercase;letter-spacing:.03em;color:var(--muted)}table.grid thead th.g-decision{background:#eef2fb;color:#26418f}table.grid td:first-child,table.grid th:first-child{position:sticky;left:0;background:#fff;z-index:1;border-right:2px solid var(--line)}table.grid thead th:first-child{z-index:3;background:#eef2fb}
table.tc{width:100%;border-collapse:collapse;font-size:12px}table.tc th,table.tc td{text-align:left;padding:7px 9px;border-bottom:1px solid var(--line);vertical-align:top}table.tc th{background:#faf9f6;font-size:11px;text-transform:uppercase;color:var(--muted)}table.tc tr.win td{background:#eef8f0}
.pill{display:inline-block;font:600 10px/1 var(--mono);text-transform:uppercase;padding:4px 8px;border-radius:999px;border:1px solid var(--line)}.pill.block,.pill.no{background:#fde8e8;border-color:#f5b5b5;color:#9b1c1c}.pill.allow,.pill.win,.pill.yes{background:#e7f6ec;border-color:#a8ddba;color:#1c6b34}.pill.challenge,.pill.maybe{background:#fdf2df;border-color:#eccd8a;color:#8a5a00}.pill.squeeze{background:#e9eefc;border-color:#b6c6f2;color:#26418f}
.muted{color:var(--muted);font-size:12px}.big{font:700 22px/1 var(--mono)}.stat{border:1px solid var(--line);border-radius:8px;padding:12px;background:#fff}.grid4{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px;margin:0 0 12px}
.res{background:#0e1116;color:#d7e0ea;border-radius:8px;padding:12px;font:12px/1.5 var(--mono);white-space:pre-wrap;max-height:340px;overflow:auto}code{background:#f2f0ea;padding:1px 5px;border-radius:4px;font-size:12px}
.split .lane{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;border:1px solid var(--line);border-radius:8px;padding:9px 12px;background:#fff;margin-bottom:6px}
.tree{font-size:12px}.tree .n{border-left:2px solid var(--line);margin:4px 0 4px 10px;padding:4px 10px}.tree .s{color:var(--muted);font-family:var(--mono);font-size:11px}
.jrow{display:grid;grid-template-columns:150px 110px 1fr;gap:8px;padding:6px 0;border-bottom:1px solid var(--line);font-size:12px}.jrow time{color:var(--muted);font-family:var(--mono);font-size:11px}
.matrix td.c{font-size:10px;text-align:center;padding:4px 3px}.matrix td.c.s{background:#e7f6ec}.matrix td.c.u{background:#faf9f6;color:#aaa}.matrix td.c.x{background:#fde8e8}
</style>
<section style="display:flex;justify-content:space-between;align-items:end;gap:14px;flex-wrap:wrap"><div><h1>Growth console</h1><p class="subtitle">Traffic, version testing, ad spend and customer journeys as one graph. Facts, provider reports, estimates and inferences are labeled, never mixed.</p></div><div><label class="muted">Ruleset </label><select id="rs" style="padding:8px;border:1px solid var(--line);border-radius:7px"></select></div></section>
<div class="tc-tabs"><button data-tab="optimize" class="on">Optimize</button><button data-tab="media">Media graph</button><button data-tab="journey">Journey</button><button data-tab="providers">Providers</button><button data-tab="proposals">Proposals</button><button data-tab="data">Data (every field)</button><button data-tab="split">Split</button><button data-tab="test">Simulate</button><button data-tab="rules">Rules</button><button data-tab="versions">Versions</button><button data-tab="lists">Lists</button><button data-tab="fields">Fields</button></div>

<div id="p-optimize" class="tc-panel on"><div class="grid4" id="opt-metrics"></div>
 <div class="tc-card"><h3>Squeeze page versions — impressions → verified (CVR). Winner in green.</h3><div style="overflow:auto"><table class="tc"><thead><tr><th>Variant</th><th>Weight</th><th>Impressions</th><th>Engaged</th><th>Verified</th><th>Approved</th><th>CVR</th><th></th></tr></thead><tbody id="opt-sqz"></tbody></table></div><p class="muted">Set weight creates a proposal (allocation_change, requires approval) — nothing moves silently.</p></div>
 <div class="tc-card"><h3>Destinations — visits → conversions</h3><div style="overflow:auto"><table class="tc"><thead><tr><th>Destination</th><th>Visits</th><th>Conversions</th><th>CVR</th></tr></thead><tbody id="opt-dst"></tbody></table></div></div></div>

<div id="p-media" class="tc-panel">
 <div class="tc-card"><h3>Import an ad account (read-only) into the graph</h3><div class="tc-row"><select id="m-acct"><option value="">loading live Meta accounts…</option></select><select id="m-days"><option value="7">last 7 days</option><option value="30" selected>last 30 days</option><option value="90">last 90 days</option></select><select id="m-brand"><option value="">(no brand)</option></select></div>
 <button class="go" id="m-import">Import / sync</button> <button class="ghost" id="m-resolve">Join ad clicks → decisions</button> <button class="ghost" id="m-register">Register page versions</button> <span id="m-out" class="muted"></span></div>
 <div class="grid4" id="m-totals"></div>
 <div class="tc-card"><h3>Account → Campaign → Ad set → Ad → Creative — spend · impressions · clicks · <b>derived</b> CTR · CPC · CPA · ROAS · site clicks joined</h3><div id="m-tree" class="tree"><p class="muted">Nothing imported yet.</p></div></div>
 <div class="tc-card"><h3>Sync runs (idempotent per window)</h3><div style="overflow:auto"><table class="tc"><thead><tr><th>When</th><th>Provider</th><th>Kind</th><th>Window</th><th>State</th><th>Counts</th></tr></thead><tbody id="m-syncs"></tbody></table></div></div></div>

<div id="p-journey" class="tc-panel"><div class="tc-card"><h3>One person, end to end</h3><div class="tc-row"><input id="j-pid" placeholder="profile id (prf_…) — from Data tab"><button class="go" id="j-go">Show journey</button></div><div id="j-out"></div></div></div>

<div id="p-providers" class="tc-panel"><div class="tc-card"><h3>Provider registry — a slot for every network; presence ≠ capability</h3><button class="ghost" id="pv-seed">Seed / refresh registry</button> <span id="pv-out" class="muted"></span><div style="overflow:auto;margin-top:10px"><table class="tc matrix"><thead id="pv-head"></thead><tbody id="pv-body"></tbody></table></div><p class="muted">green = supported (verified), grey = unverified, red = unsupported. Connections: authorized / not_connected / permission_missing / rate_limited / error.</p></div></div>

<div id="p-proposals" class="tc-panel"><div class="tc-card"><h3>Action queue — every proposed mutation, with authority, bounds and state. Nothing here executes.</h3><div style="overflow:auto"><table class="tc"><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Target</th><th>Authority</th><th>State</th><th>Reason</th></tr></thead><tbody id="pr-list"></tbody></table></div></div>
 <div class="tc-card"><h3>Evaluate a growth rule against a deployment (creates a proposal only)</h3><div class="tc-full"><textarea id="gr-text" placeholder="if spend over 500 and purchases is 0 then block"></textarea></div><div class="tc-row"><input id="gr-subject" placeholder="deployment id (mdp_…)"><input id="gr-days" placeholder="days (30)"></div><button class="go" id="gr-run">Evaluate</button><div id="gr-out" class="res" style="margin-top:10px;display:none"></div></div></div>

<div id="p-data" class="tc-panel"><div style="display:flex;gap:8px;align-items:center;margin:0 0 10px;flex-wrap:wrap"><input id="d-q" placeholder="filter rows…" style="flex:1;min-width:220px;padding:8px;border:1px solid var(--line);border-radius:7px"><button class="ghost" id="d-prev">◀ prev</button><span id="d-note" class="muted"></span><button class="ghost" id="d-next">next ▶</button><button class="ghost" id="d-cols">Columns…</button></div><div id="d-colpick" class="tc-card" style="display:none"></div><div class="grid-wrap"><table class="grid"><thead id="d-head"></thead><tbody id="d-body"></tbody></table></div><p class="muted" id="d-count" style="margin-top:8px"></p></div>
<div id="p-split" class="tc-panel"><div class="grid4" id="split-metrics"></div><div class="tc-card"><h3>How visitors split (rules in priority order)</h3><div id="split-lanes" class="split"><p class="muted">Loading…</p></div></div></div>
<div id="p-test" class="tc-panel"><div class="tc-card"><h3>Send a hypothetical visitor through the live rules — nothing is written</h3><div class="tc-row"><input id="t-country" placeholder="country (US, KP…)"><input id="t-region" placeholder="region"><input id="t-bot" placeholder="bot score 0-100"><input id="t-asorg" placeholder="ISP / org"></div><div class="tc-row"><input id="t-tags" placeholder="profile tags (vip…)"><input id="t-ua" placeholder="user agent"><input id="t-ref" placeholder="referrer host"><select id="t-known"><option value="">unknown visitor</option><option value="1">known profile</option></select></div><button class="go" id="t-run">Run</button><div id="t-out" style="margin-top:12px"></div></div></div>
<div id="p-rules" class="tc-panel"><div class="tc-card"><h3>Declare a routing rule in plain English</h3><p class="muted">e.g. <code>if country is KP then block</code> · <code>if bot score under 30 then challenge</code> · <code>if tag contains vip then send to dst_offer</code></p><div class="tc-full"><textarea id="r-text" placeholder="if &lt;condition&gt; then &lt;action&gt;"></textarea></div><div class="tc-row"><input id="r-prio" placeholder="priority (lower first)"><input id="r-name" placeholder="name"></div><button class="go" id="r-add">Add rule</button> <button class="ghost" id="r-activate">Activate ruleset</button><div id="r-out" class="muted" style="margin-top:8px"></div></div><div class="tc-card"><h3>Current rules</h3><div style="overflow:auto"><table class="tc"><thead><tr><th>#</th><th>Rule</th><th>State</th></tr></thead><tbody id="r-list"></tbody></table></div></div></div>
<div id="p-versions" class="tc-panel"><div class="tc-card"><h3>Immutable experience versions + current allocation</h3><div style="overflow:auto"><table class="tc"><thead><tr><th>Surface</th><th>v</th><th>Ref</th><th>State</th><th>Hash</th><th>Since</th></tr></thead><tbody id="v-xv"></tbody></table></div><div id="v-alloc" class="muted" style="margin-top:8px"></div></div>
 <div class="tc-card"><h3>Add a squeeze variant (creates version N+1; never overwrites)</h3><div class="tc-row"><input id="sq-name" placeholder="variant name"><input id="sq-head" placeholder="headline"><input id="sq-cta" placeholder="CTA text"><input id="sq-weight" placeholder="weight"></div><button class="go" id="sq-add">Add variant</button> <span id="sq-out" class="muted"></span></div>
 <div class="tc-card"><h3>Add a destination / A/B group</h3><div class="tc-row"><input id="dn-name" placeholder="name"><select id="dn-type"><option>redirect</option><option>inline</option></select><input id="dn-url" placeholder="url https://…"><input id="dn-hosts" placeholder="allowed hosts"></div><button class="go" id="dn-add">Add destination</button> <span id="dn-out" class="muted"></span><div class="tc-row" style="margin-top:10px"><input id="gp-name" placeholder="A/B group name"><input id="gp-a" placeholder="dest A id"><input id="gp-aw" placeholder="A weight"><input id="gp-b" placeholder="dest B id"><input id="gp-bw" placeholder="B weight"></div><button class="go" id="gp-add">Add A/B group</button> <span id="gp-out" class="muted"></span></div></div>
<div id="p-lists" class="tc-panel"><div class="grid4" id="list-counts"></div><div class="tc-card"><h3>Add a whitelist / blacklist entry</h3><div class="tc-row"><select id="l-list"><option value="allow">Whitelist</option><option value="deny">Blacklist</option></select><select id="l-kind"><option>country</option><option>visitor_hash</option><option>phone_hash</option><option>ip</option><option>cidr</option><option>asn</option><option>email_domain</option><option>tag</option><option>referrer</option><option>ua</option><option>region</option><option>device</option></select><input id="l-value" placeholder="value"><input id="l-reason" placeholder="reason (required)"></div><div class="tc-row"><select id="l-effect"><option value="decide">decide</option><option value="skip_challenge">skip Turnstile</option><option value="route">route to destination</option><option value="score">adjust risk</option></select><input id="l-eff" placeholder="dest id (route) / delta (score)"></div><button class="go" id="l-add">Add</button> <span id="l-out" class="muted"></span></div><div class="tc-card"><h3>Seed from JustCloakIt history</h3><button class="go" id="seed-run">Seed a batch</button> <button class="ghost" id="seed-auto">Run to completion</button><div id="seed-out" class="muted" style="margin-top:8px"></div></div></div>
<div id="p-fields" class="tc-panel"><div class="tc-card"><h3>Every field captured per visitor — the Data columns</h3><input id="f-q" placeholder="filter fields…" style="width:100%;padding:8px;border:1px solid var(--line);border-radius:7px;margin:0 0 10px"><div style="overflow:auto;max-height:600px"><table class="tc"><thead><tr><th>Name</th><th>Group</th><th>Type</th><th>What it is</th><th>Values</th></tr></thead><tbody id="f-list"></tbody></table></div></div></div>

<script>
const T='/api/traffic',G='/api/growth',$=(s)=>document.querySelector(s);
async function api(base,p,o){const r=await fetch(base+p,Object.assign({credentials:'same-origin',headers:{'content-type':'application/json'}},o||{}));return r.json();}
const ta=(p,o)=>api(T,p,o), ga=(p,o)=>api(G,p,o);
let RS=null,SNAP={rulesets:[],destinations:[],campaigns:[]},GRID={columns:[],rows:[],page:1,pages:1},HIDDEN=new Set(),BRANDS=[];
const esc=(s)=>String(s==null?'':s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const num=(v,d=0)=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});const money=(v)=>v==null?'—':'$'+Number(v).toLocaleString(undefined,{maximumFractionDigits:2});const pct=(v)=>v==null?'—':Number(v).toFixed(1)+'%';
function pill(txt){const p=(txt||'').toLowerCase();let c='';if(p.includes('deny')||p.includes('block')||p==='rejected')c='block';else if(p.includes('allow')||p==='approved'||p==='executed'||p==='authorized')c='allow';else if(p.includes('verify')||p.includes('challenge')||p==='proposed')c='challenge';else if(p.includes('squeeze'))c='squeeze';return '<span class="pill '+c+'">'+esc(txt||'')+'</span>';}
document.querySelectorAll('.tc-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tc-tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.tc-panel').forEach(x=>x.classList.remove('on'));$('#p-'+b.dataset.tab).classList.add('on');});
async function boot(){const rl=await ta('/rulesets');SNAP=rl;const sel=$('#rs');sel.innerHTML=(rl.rulesets||[]).map(r=>'<option value="'+r.id+'">'+esc(r.name||r.id)+' ('+r.state+')</option>').join('')||'<option value="">none</option>';RS=(rl.rulesets[0]||{}).id;sel.onchange=()=>{RS=sel.value;loadSplit();loadRules();};loadOptimize();loadMedia();loadProviders();loadProposals();loadGrid();loadFields();loadSplit();loadRules();loadLists();loadVersions();}

async function loadOptimize(){const o=await ta('/optimize'),m=await ta('/metrics');const mm=m.metrics||{};$('#opt-metrics').innerHTML=[['requests',mm.requests],['approved',mm.approved],['blocked',mm.blocked],['challenged',mm.challenged],['squeeze views',(mm.funnel||{}).squeeze_impressions],['verified',(mm.funnel||{}).verified]].map(([k,v])=>'<div class="stat"><div class="big">'+(v||0)+'</div><div class="muted">'+k+'</div></div>').join('');
 $('#opt-sqz').innerHTML=(o.squeeze_variants||[]).map(s=>'<tr class="'+(s.winner?'win':'')+'"><td><b>'+esc(s.name)+'</b><br><span class="muted">'+esc(s.id)+'</span></td><td>'+esc(s.weight)+'</td><td>'+num(s.impressions)+'</td><td>'+num(s.engaged)+'</td><td>'+num(s.conversions)+'</td><td>'+num(s.approved)+'</td><td><b>'+pct(s.cvr)+'</b></td><td>'+(s.winner?'<span class="pill win">winner</span>':'')+' <button class="ghost" data-w="'+esc(s.id)+'">propose weight</button></td></tr>').join('')||'<tr><td colspan=8 class="muted">no squeeze traffic yet</td></tr>';
 $('#opt-dst').innerHTML=(o.destinations||[]).map(d=>'<tr class="'+(d.winner?'win':'')+'"><td><code>'+esc(d.id)+'</code>'+(d.winner?' <span class="pill win">winner</span>':'')+'</td><td>'+num(d.visits)+'</td><td>'+num(d.conversions)+'</td><td><b>'+pct(d.cvr)+'</b></td></tr>').join('')||'<tr><td colspan=4 class="muted">none</td></tr>';
 document.querySelectorAll('#opt-sqz button[data-w]').forEach(b=>b.onclick=async()=>{const w=prompt('Proposed weight for '+b.dataset.w+':','3');if(!w)return;const r=await ga('/proposals',{method:'POST',body:JSON.stringify({actor:'owner',action:'allocation_change',target_type:'squeeze',target_id:b.dataset.w,provider_id:'miscsubjects_engine',after:{weight:Number(w)},reason:'console: shift weight to winner',required_authority:'campaign_write'})});alert(r.ok?'Proposal '+r.id+' created (state: proposed). Approve it in Proposals.':'Error');loadProposals();});}

async function loadMedia(){const a=await ga('/media/accounts?live=1');const live=(a.live&&a.live.accounts)||[];const imp=new Set((a.imported||[]).map(x=>x.external_id));$('#m-acct').innerHTML=live.length?live.map(x=>'<option value="'+esc(x.external_id)+'">'+esc(x.name||x.external_id)+' · '+esc(x.external_id)+(x.spent?' · spent '+money(x.spent):'')+(imp.has(x.external_id)?' · imported':'')+'</option>').join(''):'<option value="">'+esc((a.live&&a.live.error)||'no live accounts')+'</option>';
 const br=await ga('/brands');BRANDS=br.brands||[];$('#m-brand').innerHTML='<option value="">(no brand)</option>'+BRANDS.map(b=>'<option value="'+b.id+'">'+esc(b.name)+(b.is_self?' (self)':'')+'</option>').join('');
 const g=await ga('/media/graph?days=30');const D=g.deployments||[];const T2=(k)=>D.reduce((s,x)=>s+(x.primitives?.[k]||0),0);
 $('#m-totals').innerHTML=[['accounts',(g.accounts||[]).length],['campaigns',(g.initiatives||[]).length],['ads',D.length],['creatives',(g.creatives||[]).length],['spend 30d',money(T2('spend'))],['impressions',num(T2('impressions'))],['clicks',num(T2('clicks'))],['purchases',num(T2('purchases'))],['revenue',money(T2('revenue'))]].map(([k,v])=>'<div class="stat"><div class="big" style="font-size:18px">'+v+'</div><div class="muted">'+k+'</div></div>').join('');
 const st=(x)=>{const p=x.primitives||{},d=x.derived||{};return '<span class="s">spend '+money(p.spend)+' · impr '+num(p.impressions)+' · clicks '+num(p.clicks)+' · CTR '+pct(d.ctr_pct)+' · CPC '+money(d.cpc)+' · purchases '+num(p.purchases)+' · CPA '+money(d.cpa)+' · ROAS '+(d.roas!=null?Number(d.roas).toFixed(2)+'×':'—')+'</span>';};
 const byI={},byG={};for(const gr of g.groups||[])(byI[gr.initiative_id]=byI[gr.initiative_id]||[]).push(gr);for(const dp of D)(byG[dp.group_id]=byG[dp.group_id]||[]).push(dp);const crs={};for(const c of g.creatives||[])crs[c.id]=c;
 let html='';for(const ac of g.accounts||[]){html+='<div class="n"><b>'+esc(ac.provider_id)+' · '+esc(ac.external_id)+'</b> '+st(ac);for(const i of (g.initiatives||[]).filter(x=>x.account_id===ac.id)){html+='<div class="n"><b>'+esc(i.name)+'</b> <span class="muted">'+esc(i.status)+' · '+esc(i.objective||'')+(i.daily_budget?' · '+money(i.daily_budget)+'/day':'')+'</span> '+st(i);for(const gr of byI[i.id]||[]){html+='<div class="n"><b>'+esc(gr.name)+'</b> <span class="muted">'+esc(gr.status)+'</span> '+st(gr);for(const dp of byG[gr.id]||[]){const c=crs[dp.creative_id];html+='<div class="n"><b>'+esc(dp.name)+'</b> <span class="muted">'+esc(dp.status)+'</span> '+st(dp)+(dp.site?' <span class="pill">'+dp.site.site_clicks+' site clicks · '+dp.site.visitors+' visitors</span>':'')+(c?'<div class="muted">creative: '+esc(c.name||'')+' · '+esc(c.format||'')+'</div>':'')+'</div>';}html+='</div>';}html+='</div>';}html+='</div>';}
 $('#m-tree').innerHTML=html||'<p class="muted">Nothing imported yet — pick an account and Import.</p>';
 const sy=await ga('/syncs');$('#m-syncs').innerHTML=(sy.syncs||[]).slice(0,12).map(s=>'<tr><td class="muted">'+esc(String(s.started_at).slice(0,16))+'</td><td>'+esc(s.provider_id)+'</td><td>'+esc(s.kind)+'</td><td class="muted">'+esc(s.window_start)+' → '+esc(s.window_end)+'</td><td>'+pill(s.state)+'</td><td class="muted">'+esc((s.counts_json||'').slice(0,90))+'</td></tr>').join('')||'<tr><td colspan=6 class="muted">none</td></tr>';}
$('#m-import').onclick=async()=>{const id=$('#m-acct').value;if(!id)return;$('#m-out').textContent='Importing…';const r=await ga('/media/import',{method:'POST',body:JSON.stringify({provider_id:'meta_ads',account_id:id,days:Number($('#m-days').value),brand_id:$('#m-brand').value||null})});const c=r.counts||{};$('#m-out').textContent=(r.ok?'Imported':'Partial')+': '+c.initiatives+' campaigns · '+c.groups+' ad sets · '+c.deployments+' ads · '+c.creatives+' creatives · '+c.observations+' observations · '+c.not_collected+' not_collected'+(r.replay_of?' · replay of '+r.replay_of:'')+(r.errors&&r.errors.length?' · errors: '+r.errors.join('; '):'');loadMedia();};
$('#m-resolve').onclick=async()=>{const r=await ga('/clicks/resolve',{method:'POST',body:JSON.stringify({limit:1000})});$('#m-out').textContent='Scanned '+r.scanned+' decisions, joined '+r.linked+' ad clicks.';loadMedia();};
$('#m-register').onclick=async()=>{const r=await ga('/versions/register',{method:'POST',body:'{}'});$('#m-out').textContent='Registered '+r.created+' new versions ('+r.total+' total).';loadVersions();};

$('#j-go').onclick=async()=>{const pid=$('#j-pid').value.trim();if(!pid)return;const j=await ga('/journey/'+encodeURIComponent(pid));const rows=[];for(const c of j.clicks||[])rows.push([c.ts,'ad click','<b>'+esc(c.provider_id||c.click_kind)+'</b>'+(c.deployment_external_id?' · ad '+esc(c.deployment_external_id):'')+(c.experience_version_id?' → '+esc(c.experience_version_id):'')]);for(const d of j.decisions||[])rows.push([d.ts,'decision',pill(d.experience||('→ '+(d.destination_id||'')))+' <span class="muted">'+esc(d.reason||'')+(d.experience_version_id?' · '+esc(d.experience_version_id):'')+'</span>']);for(const e of j.events||[])rows.push([e.ts,'event','<b>'+esc(e.event_type||e.kind)+'</b>']);for(const o of j.orders||[])rows.push([o.ts,'order','<b>'+money(o.net)+'</b> <span class="muted">'+esc(o.provider_id)+' '+esc(o.external_id)+'</span>']);rows.sort((a,b)=>String(a[0]).localeCompare(String(b[0])));const e=j.economics;$('#j-out').innerHTML=(e?'<div class="grid4"><div class="stat"><div class="big">'+money(e.net)+'</div><div class="muted">net revenue</div></div><div class="stat"><div class="big">'+num(e.orders)+'</div><div class="muted">orders</div></div><div class="stat"><div class="big">'+money(e.realized_ltv)+'</div><div class="muted">realized LTV</div></div><div class="stat"><div class="big">'+money(e.refunds)+'</div><div class="muted">refunds</div></div></div>':'<p class="muted">No economics for this profile yet (commerce adapter populates it).</p>')+(rows.map(r=>'<div class="jrow"><time>'+esc(String(r[0]).slice(0,19))+'</time><span class="muted">'+r[1]+'</span><span>'+r[2]+'</span></div>').join('')||'<p class="muted">No journey rows.</p>');};

async function loadProviders(){const p=await ga('/providers');const cols=p.capability_columns||[];$('#pv-head').innerHTML='<tr><th>Provider</th><th>Category</th><th>Connection</th>'+cols.map(c=>'<th title="'+c+'">'+esc(c.replace('cap_','').replace(/_/g,' ').slice(0,10))+'</th>').join('')+'</tr>';const conn={};for(const c of p.connections||[])conn[c.provider_id]=c;$('#pv-body').innerHTML=(p.providers||[]).map(r=>'<tr><td><b>'+esc(r.name)+'</b><br><span class="muted">'+esc(r.id)+'</span></td><td class="muted">'+esc(r.category)+'</td><td>'+(conn[r.id]?pill(conn[r.id].state):'<span class="muted">no slot</span>')+'</td>'+cols.map(c=>{const v=r[c];return '<td class="c '+(v==='supported'?'s':v==='unsupported'?'x':'u')+'" title="'+esc(v)+'">'+(v==='supported'?'✓':v==='unsupported'?'✗':'·')+'</td>';}).join('')+'</tr>').join('')||'<tr><td colspan=21 class="muted">registry empty — click Seed</td></tr>';}
$('#pv-seed').onclick=async()=>{const r=await ga('/providers/seed',{method:'POST',body:'{}'});$('#pv-out').textContent='Registry: '+r.total+' slots ('+r.created+' new, '+r.updated+' refreshed) · '+r.connections+' connections';loadProviders();};

async function loadProposals(){const p=await ga('/proposals');$('#pr-list').innerHTML=(p.proposals||[]).map(x=>'<tr><td class="muted">'+esc(String(x.ts).slice(0,16))+'</td><td>'+esc(x.actor)+'</td><td><b>'+esc(x.action)+'</b></td><td class="muted">'+esc(x.target_type)+' '+esc(x.target_id)+'</td><td>'+esc(x.required_authority)+'</td><td>'+pill(x.approval_state)+'</td><td class="muted">'+esc((x.reason||'').slice(0,80))+'</td></tr>').join('')||'<tr><td colspan=7 class="muted">no proposals yet</td></tr>';}
$('#gr-run').onclick=async()=>{const r=await ga('/rules/evaluate',{method:'POST',body:JSON.stringify({text:$('#gr-text').value,subject_type:'deployment',subject_id:$('#gr-subject').value,days:Number($('#gr-days').value)||30,rule_name:'console'})});const el=$('#gr-out');el.style.display='block';el.textContent=JSON.stringify({matched:r.matched,metrics:r.metrics,proposal:r.proposal,provider_calls:r.provider_calls,error:r.error||r.message},null,1);loadProposals();};

async function loadGrid(){const g=await ta('/grid?per_page=50&page='+GRID.page);GRID.columns=g.columns||[];GRID.rows=g.rows||[];GRID.pages=g.pages||1;renderGrid();$('#d-note').textContent='page '+g.page+' / '+g.pages;$('#d-count').textContent=(g.total||0)+' decisions · '+GRID.columns.length+' columns';}
function renderGrid(){const q=($('#d-q').value||'').toLowerCase();const cols=GRID.columns.filter(c=>!HIDDEN.has(c.key));$('#d-head').innerHTML='<tr>'+cols.map(c=>'<th class="'+(c.group==='decision'?'g-decision':'')+'" title="'+esc(c.key)+'">'+esc(c.label)+'</th>').join('')+'</tr>';const rows=GRID.rows.filter(r=>!q||Object.values(r).join(' ').toLowerCase().includes(q));$('#d-body').innerHTML=rows.map(r=>'<tr>'+cols.map(c=>{let v=r[c.key];if(c.key==='experience'||c.key==='outcome')v=v?pill(v):'';return '<td>'+(typeof v==='string'&&v.startsWith('<span')?v:esc(v))+'</td>';}).join('')+'</tr>').join('')||'<tr><td>No decisions yet.</td></tr>';}
$('#d-q').oninput=renderGrid;$('#d-prev').onclick=()=>{if(GRID.page>1){GRID.page--;loadGrid();}};$('#d-next').onclick=()=>{if(GRID.page<GRID.pages){GRID.page++;loadGrid();}};$('#d-cols').onclick=()=>{const el=$('#d-colpick');if(el.style.display==='none'){el.style.display='block';el.innerHTML='<b>Show columns</b><br>'+GRID.columns.map(c=>'<label style="display:inline-block;margin:4px 10px 4px 0;font-size:12px"><input type=checkbox data-c="'+c.key+'" '+(HIDDEN.has(c.key)?'':'checked')+'> '+esc(c.label)+'</label>').join('');el.querySelectorAll('input').forEach(i=>i.onchange=()=>{if(i.checked)HIDDEN.delete(i.dataset.c);else HIDDEN.add(i.dataset.c);renderGrid();});}else el.style.display='none';};
async function loadSplit(){const m=await ta('/metrics');const mm=m.metrics||{};$('#split-metrics').innerHTML=[['requests',mm.requests],['approved',mm.approved],['blocked',mm.blocked],['challenged',mm.challenged]].map(([k,v])=>'<div class="stat"><div class="big">'+(v||0)+'</div><div class="muted">'+k+'</div></div>').join('');const rp=await ta('/rules/plain?ruleset_id='+encodeURIComponent(RS||''));const lanes=(rp.rules||[]).map(r=>'<div class="lane"><div><b>'+esc(r.name||r.id)+'</b> <span class="muted">#'+r.priority+(r.enabled?'':' · off')+'</span><br><span class="muted">'+esc(r.plain.split(' then ')[0])+'</span></div><div>'+pill(r.plain.split(' then ')[1]||'')+'</div></div>').join('');const dd=(mm.destination_distribution||[]).map(d=>'<div class="lane"><div>went to <code>'+esc(d.k)+'</code></div><div><span class="pill">'+d.n+'</span></div></div>').join('');$('#split-lanes').innerHTML=(lanes||'<p class="muted">No rules yet.</p>')+(dd?'<h3 style="margin:14px 0 6px;font-size:13px">Where live traffic went (24h)</h3>'+dd:'');}
async function loadRules(){const rp=await ta('/rules/plain?ruleset_id='+encodeURIComponent(RS||''));$('#r-list').innerHTML=(rp.rules||[]).map((r,i)=>'<tr><td>'+(i+1)+'</td><td><b>'+esc(r.plain)+'</b><br><span class="muted">'+esc(r.id)+'</span></td><td>'+(r.enabled?'on':'off')+'</td></tr>').join('')||'<tr><td colspan=3 class="muted">none</td></tr>';}
async function loadFields(){const f=await ta('/fields');window.__F=f.fields||[];renderFields();$('#f-q').oninput=renderFields;}
function renderFields(){const q=($('#f-q').value||'').toLowerCase();$('#f-list').innerHTML=(window.__F||[]).filter(x=>!q||(x.field+x.path+x.description).toLowerCase().includes(q)).map(x=>'<tr><td><b>'+esc(x.field)+'</b><br><span class="muted">'+esc(x.path)+'</span></td><td>'+esc(x.group)+'</td><td>'+esc(x.type)+'</td><td>'+esc(x.description)+'</td><td>'+esc(x.values?(Array.isArray(x.values)?x.values.join(', '):x.values):'')+'</td></tr>').join('');}
async function loadLists(){const s=await ta('/seed-history',{method:'POST',body:JSON.stringify({limit:1,seed_limit:1})}).catch(()=>({}));$('#list-counts').innerHTML=[['whitelist (history)',s.whitelist],['blacklist (history)',s.blacklist]].map(([k,v])=>'<div class="stat"><div class="big">'+num(v)+'</div><div class="muted">'+k+'</div></div>').join('');}
async function loadVersions(){const v=await ga('/versions');$('#v-xv').innerHTML=(v.versions||[]).map(x=>'<tr><td><code>'+esc(x.experience_key)+'</code></td><td>v'+esc(x.version)+'</td><td class="muted">'+esc(x.ref_id||'')+'</td><td>'+pill(x.state)+'</td><td class="muted">'+esc((x.artifact_hash||'').slice(0,10))+'</td><td class="muted">'+esc(String(x.created_at).slice(0,10))+'</td></tr>').join('')||'<tr><td colspan=6 class="muted">none — Media tab → Register page versions</td></tr>';$('#v-alloc').innerHTML=(v.allocation_policies||[]).map(p=>'<div>allocation v'+p.version+' for <code>'+esc(p.experience_id)+'</code>: '+esc(p.policy_json)+'</div>').join('')||'';}
function campaignId(){return (SNAP.campaigns&&SNAP.campaigns[0]||{}).id;}
$('#t-run').onclick=async()=>{const entry=(SNAP.rulesets.find(r=>r.id===RS)||{}).entry?.[0]?.entry||'acceptance';const sim={url:location.origin+'/go/'+entry,entry,ruleset_id:RS,country:$('#t-country').value||undefined,region:$('#t-region').value||undefined,bot_score:$('#t-bot').value?Number($('#t-bot').value):undefined,as_org:$('#t-asorg').value||undefined,user_agent:$('#t-ua').value||undefined,profile:{known:$('#t-known').value==='1',tags:($('#t-tags').value||'').split(',').map(s=>s.trim()).filter(Boolean)}};if($('#t-ref').value)sim.headers={referer:'https://'+$('#t-ref').value};const r=await ta('/explain',{method:'POST',body:JSON.stringify({sim})});const d=r.decision||{};$('#t-out').innerHTML='<div class="tc-card"><b>Sent to:</b> '+pill(d.experience||('send to '+(d.destination_id||'—')))+'<br><span class="muted">reason: '+esc(d.reason||'')+' · matched: '+esc((d.matched_rules||[]).join(', ')||'none')+'</span></div><div class="res">'+esc(JSON.stringify({experience:d.experience,destination:d.destination_id,outcome:d.outcome,risk:d.risk,reasons:(d.reasons||[]).slice(0,10)},null,1))+'</div>';};
$('#r-add').onclick=async()=>{const r=await ta('/rule/plain',{method:'POST',body:JSON.stringify({ruleset_id:RS,text:$('#r-text').value,priority:$('#r-prio').value||undefined,name:$('#r-name').value||undefined})});$('#r-out').textContent=r.ok?('Added: '+r.plain+' — Activate to make live.'):('Error: '+(r.message||r.error));if(r.ok){$('#r-text').value='';loadRules();}};
$('#r-activate').onclick=async()=>{const r=await ta('/rulesets/'+encodeURIComponent(RS)+'/activate',{method:'POST',body:JSON.stringify({note:'console'})});$('#r-out').textContent=r.ok?('Activated — revision '+r.revision+'.'):('Error: '+JSON.stringify(r.errors||r.error));loadSplit();};
$('#sq-add').onclick=async()=>{const cid=campaignId();if(!cid){$('#sq-out').textContent='no campaign';return;}const r=await ta('/config',{method:'POST',body:JSON.stringify({table:'traffic_squeeze_pages',patch:{__create:true,campaign_id:cid,name:$('#sq-name').value,headline:$('#sq-head').value,cta_text:$('#sq-cta').value,message_template:'JOIN {code}',weight:Number($('#sq-weight').value)||1,status:'active',enabled:1}})});$('#sq-out').textContent=r.ok?'Added '+r.id:('Error: '+JSON.stringify(r.errors||r.error));if(r.ok){await ga('/versions/register',{method:'POST',body:'{}'});loadVersions();loadOptimize();}};
$('#dn-add').onclick=async()=>{const patch={__create:true,name:$('#dn-name').value,type:$('#dn-type').value,enabled:1};if($('#dn-url').value)patch.url=$('#dn-url').value;if($('#dn-hosts').value)patch.allowed_hosts_json=JSON.stringify($('#dn-hosts').value.split(',').map(s=>s.trim()).filter(Boolean));const r=await ta('/config',{method:'POST',body:JSON.stringify({table:'traffic_destinations',patch})});$('#dn-out').textContent=r.ok?'Added '+r.id:('Error: '+JSON.stringify(r.errors||r.error));};
$('#gp-add').onclick=async()=>{const r=await ta('/config',{method:'POST',body:JSON.stringify({table:'traffic_destinations',patch:{__create:true,name:$('#gp-name').value||'A/B group',type:'group',enabled:1,sticky:1,members_json:JSON.stringify([{id:$('#gp-a').value,weight:Number($('#gp-aw').value)||1},{id:$('#gp-b').value,weight:Number($('#gp-bw').value)||1}])}})});$('#gp-out').textContent=r.ok?'Added group '+r.id+' — point a rule at it, then Activate.':('Error: '+JSON.stringify(r.errors||r.error));};
$('#l-add').onclick=async()=>{const patch={__create:true,list:$('#l-list').value,kind:$('#l-kind').value,value:$('#l-value').value,reason:$('#l-reason').value,effect:$('#l-effect').value};if($('#l-effect').value==='route'&&$('#l-eff').value)patch.effect_json=JSON.stringify({destination:$('#l-eff').value});if($('#l-effect').value==='score'&&$('#l-eff').value)patch.effect_json=JSON.stringify({delta:Number($('#l-eff').value)});const r=await ta('/config',{method:'POST',body:JSON.stringify({table:'traffic_list_entries',patch})});$('#l-out').textContent=r.ok?'Added.':('Error: '+JSON.stringify(r.errors||r.error));};
$('#seed-run').onclick=async()=>{$('#seed-out').textContent='Seeding…';const r=await ta('/seed-history',{method:'POST',body:JSON.stringify({seed_limit:30000})});$('#seed-out').textContent='Imported '+r.imported+' · whitelist '+num(r.whitelist)+' · blacklist '+num(r.blacklist);loadLists();};
$('#seed-auto').onclick=async()=>{let ic=null,sc=null,n=0;$('#seed-out').textContent='Running…';while(n<60){const r=await ta('/seed-history',{method:'POST',body:JSON.stringify({import_cursor:ic,seed_cursor:sc,limit:400,seed_limit:30000})});ic=r.import_cursor;sc=r.seed_cursor;n++;$('#seed-out').textContent='Batch '+n+': whitelist '+num(r.whitelist)+' · blacklist '+num(r.blacklist);if(r.import_done&&r.seed_done)break;}loadLists();};
boot();
</script>`;

export async function onRequestGet() {
  return new Response(shellHtml({ activeHref: '/admin/traffic', title: 'Growth console', body: BODY }), { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } });
}
