#!/usr/bin/env node
// POINTER FILES ARE GENERATED PROJECTIONS — they carry no authority.
//
// CLAUDE.md, STATE.md, AGENTS.md and handoff notes used to hold the rules, the unfinished work and
// the agent instructions. No agent other than the one running could read them, no auditor could
// check them, and every owner correction became another line in a file the next agent would never
// open. The authority is now the canonical work object.
//
// This script regenerates each file from the live object. Running it is idempotent, and
// scripts/check-pointer-files.mjs fails the deploy if any of them has grown back into carrying
// rules, state or priorities. Editing one by hand changes nothing: nothing reads them.
//
// Usage: node scripts/sync_pointer_files.mjs [--check]

import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const BASE = process.env.MISC_BASE || 'https://miscsubjects.com';
const CANON = `${BASE}/a/the-work-object`;

export const POINTER_FILES = ['STATE.md', 'AGENTS.md'];

function pointer(name, counts) {
  return `# Look here for your directions: ${CANON}

This file is a generated projection. It carries no rules, no state, no priorities, no unfinished
work and no acceptance criteria. Editing it changes nothing, because nothing reads it.

The authority is the canonical work object:

- Human projection:   ${CANON}
- Machine projection: ${BASE}/api/work
- Cold start:         ${BASE}/api/work/bootstrap
- Audit chain:        ${BASE}/api/work/audit
- The law:            ${BASE}/a/agent-work-law

Work exists only as a task object. Lease one (\`POST ${BASE}/api/work/lease\`), do exactly what it
says, submit your evidence (\`POST ${BASE}/api/work/task/<id>/submit\`), and let the infrastructure
run the acceptance tests and set the state. You cannot complete a task by saying you completed it.

${counts ? `At generation time: ${counts}.\n` : ''}
Regenerated by scripts/sync_pointer_files.mjs. Previous contents of this file are in git history;
nothing was carried forward, because none of it was authoritative.
`;
}

const args = process.argv.slice(2);
const check = args.includes('--check');

// A POINTER FILE MUST NOT CARRY A VALUE THAT CHANGES EVERY TIME ANYTHING HAPPENS.
//
// These files used to end with "... · audit head <12 hex>". The audit head moves on every single work
// action — every lease, every submission, every repair. So this script rewrote both files on virtually
// every run, the ship's own dirty-tree check then refused to deploy because they were modified, and the
// only way forward was to claim the files, commit them, and ship again. That happened five times in one
// session on 2026-08-05, and each round cost a deploy.
//
// The ship was generating its own blocker. A pointer's job is to say where the authority lives, and the
// head hash is not that — it is a live value, and the live value belongs at the live URL. The counts
// stay, because they move slowly enough to be informative and stable enough not to churn on every
// action; the head is now named as something to fetch rather than embedded as something to go stale.
let counts = '';
try {
  const r = await fetch(`${BASE}/api/work`);
  const j = await r.json();
  const c = j.counts || {};
  counts = Object.entries(c).filter(([, n]) => n > 0).map(([s, n]) => `${n} ${s}`).join(', ')
    + ` · ${(j.governing_invariants || []).length} governing invariants`
    + ' · current audit head: GET /api/work/audit';
} catch {
  counts = '';
}

let wrote = 0;
for (const name of POINTER_FILES) {
  const path = join(ROOT, name);
  const next = pointer(name, counts);
  const prev = await readFile(path, 'utf8').catch(() => '');
  if (prev === next) continue;
  if (check) {
    console.log(JSON.stringify({ ok: false, file: name, error: 'pointer_file_out_of_date' }));
    process.exit(1);
  }
  await writeFile(path, next, 'utf8');
  wrote += 1;
}
console.log(JSON.stringify({ ok: true, law: 'POINTER_FILES_ARE_PROJECTIONS', files: POINTER_FILES, rewritten: wrote, canonical: CANON }));
